### ISSUE TITLE
What is the purpose?

### ISSUE THREAD

**Issue by arttwart** [schematico/trevor#13]
Sorry, I tried to read explainment a few times but I couldn't understand.

I was searching a Redis Bungee for Velocity for some reason. I found Trevor, but I have no idea what is it. Is this thing Redis Bungee for Velocity?

Is Trevor written from zero or is it fork of Redis Bungee or something?

I'm sorry again.

**Comment by Techdaan** [comment]
Hey there! I think Trevor is written from zero, it's not a fork of RedisBungee. They are not compatible either, as far as I know. The purpose is pretty much the same though - synchronizing data between different proxies. This notifies all proxies when a player logs in, switches servers, logs out. But for example also prevents one player from connecting to several proxies at a time.

**Comment by arttwart** [comment]
So the same with Redis Bungee I guess, but the updated and renewed one.

Will an administrator be able to see every server accross proxies by typing **/server**? I read something about punishment system. When you ban someone from A proxy, what happens in B proxy? Is player banning from B proxy too or does it depend on punishment plugin?

**Comment by Techdaan** [comment]
No, administrators would not be able to see every server across proxies. You'll have to configure the servers on every proxy (in velocity.toml). You could write a plugin to sync these, or load them from a database though. I believe `/glist` is not updated/changed to support Trevor either.

Banning would depend on the banning plugin. I think FawksX has a fork of AdvancedBans that supports Velocity Trevor here: https://github.com/FawksX/AdvancedBan/tree/feature/trevor

Trevor primarily gives plugin developers/authors the tools to support multi-proxy setups, and handles some of the essentials. Anything beyond that is up to plugins to implement (kicking, delegating votes from votifier etc...).

**Comment by arttwart** [comment]
Understood really well. Thank you for helping.
